apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-ledger-chart.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}

